version: '3.7'
services:

  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: testkuatz
    container_name: testkuatz
    restart: unless-stopped
    tty: true
    environment:
      APP_NAME: testkuatz
      DB_CONNECTION: mysql
      DB_HOST: fprdb
      DB_DATABASE: testkuatz
      DB_USERNAME: root
      DB_PASSWORD: secret
    working_dir: /var/www
    volumes:
       - ./:/var/www
       - /var/www/vendor
       - /var/www/node_modules
    ports:
      - 85:80
    networks:
      - shared_network
networks:
  shared_network:
    external: true